version: '3.7'

services:
  app:
    image: webdevops/php-nginx-dev:7.3
    environment:
      WEB_DOCUMENT_ROOT: '/app/public'
      APP_ENV: 'dev'
    volumes:
      - .:/app
    ports:
      - 80:80
      - 8002:8002
  mariadb:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: workout
    ports:
      - 3306:3306


volumes:
  mariadb_data:
    driver: local
