App\Entity\Message:
  itemOperations: ['get']
  collectionOperations: []
  attributes:
    pagination_items_per_page: 10
    normalization_context:
      groups: ['message:read']
  subresourceOperations:
    api_channels_messages_get_subresource:
      normalization_context:
        groups: ['message_subresource:read']
